### ISSUE TITLE
"Already Signed In" message shows for a user when they switch their wallet address

### ISSUE THREAD

**Issue by farque65** [moonshotcollective/d-tips#25]
- User cannot sign in with a different wallet address after completing a successful sign in
- The user address should refresh on wallet address change

**Comment by codenamejason** [comment]
I could not reproduce this error.

**Comment by codenamejason** [comment]
I tried with a few MM account and was able to sign in for each one. Only when I returned to a previously used account did it say already signed in.

**Comment by farque65** [comment]
I tested this a few more times. I am not seeing it happen. I will remove this. The address refreshes with each new connection.
